package main

var products = []Product{
	// Outerwear (12 items)
	{
		ID:          "1",
		Title:       "Oversized Linen Blazer - Seoul Collection",
		Price:       189,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/1.jpg",
		Description: "A modern take on the classic blazer. Crafted from premium linen, this oversized piece offers sophisticated elegance for every occasion. Perfect layering piece that transitions effortlessly from office to evening.",
	},
	{
		ID:          "5",
		Title:       "Structured Wool Coat - Seoul Designer",
		Price:       299,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/2.jpg",
		Description: "The ultimate investment piece. This structured wool coat combines Korean minimalism with European sophistication. Meticulously crafted from premium wool.",
	},
	{
		ID:          "9",
		Title:       "Classic Trench Coat - Seoul Studio",
		Price:       249,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/3.jpg",
		Description: "Timeless elegance meets modern design. This trench coat is the perfect canvas for any outfit, with refined tailoring and premium fabric that will last for years.",
	},
	{
		ID:          "10",
		Title:       "Lightweight Denim Jacket - Korean Brand",
		Price:       129,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/1.jpg",
		Description: "Versatile and effortless. This denim jacket adds the perfect touch to any wardrobe. Quality Korean craftsmanship ensures durability and comfort.",
	},
	{
		ID:          "11",
		Title:       "Wool Blend Cardigan - Seoul Collection",
		Price:       159,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/2.jpg",
		Description: "Layering perfection. This cardigan blends warmth with style, ideal for transitional seasons and versatile styling options.",
	},
	{
		ID:          "12",
		Title:       "Formal Blazer Set - Designer Piece",
		Price:       219,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/3.jpg",
		Description: "Professional and polished. Perfect for business meetings and formal occasions, this blazer exudes confidence and sophistication.",
	},
	{
		ID:          "13",
		Title:       "Linen Blend Jacket - Summer Essential",
		Price:       139,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/1.jpg",
		Description: "Breathable and elegant. Ideal for warmer months, this jacket offers style without the bulk.",
	},
	{
		ID:          "14",
		Title:       "Cashmere Wrap - Luxury Collection",
		Price:       279,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/2.jpg",
		Description: "Ultimate luxury. This cashmere wrap adds sophistication to any outfit while providing warmth and comfort.",
	},
	{
		ID:          "15",
		Title:       "Oversized Coat - Street Style",
		Price:       269,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/3.jpg",
		Description: "Fashion-forward and comfortable. This oversized coat is perfect for creating a statement look.",
	},
	{
		ID:          "16",
		Title:       "Wool Peacoat - Classic Style",
		Price:       229,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/1.jpg",
		Description: "A timeless classic. This peacoat never goes out of style and pairs with everything.",
	},
	{
		ID:          "17",
		Title:       "Linen Shirt Jacket - Lightweight",
		Price:       149,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/2.jpg",
		Description: "Perfect for layering. This shirt jacket offers style and functionality.",
	},
	{
		ID:          "18",
		Title:       "Tailored Blazer - Office Essential",
		Price:       199,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/3.jpg",
		Description: "Professional elegance. This blazer is a must-have for any modern woman's wardrobe.",
	},

	// Tops (12 items)
	{
		ID:          "2",
		Title:       "Premium Cotton Shirt - Seoul Designer",
		Price:       79,
		Category:    "Tops",
		ImageURL:    "/images/tops/1.jpg",
		Description: "Timeless simplicity with impeccable attention to detail. This pristine white shirt is a wardrobe essential.",
	},
	{
		ID:          "19",
		Title:       "Silk Blouse - Elegant Design",
		Price:       119,
		Category:    "Tops",
		ImageURL:    "/images/tops/2.jpg",
		Description: "Luxurious and refined. This silk blouse elevates any look with its smooth drape and elegant design.",
	},
	{
		ID:          "20",
		Title:       "Basic Tee - Pure White",
		Price:       49,
		Category:    "Tops",
		ImageURL:    "/images/tops/3.jpg",
		Description: "The foundation of every wardrobe. High-quality basics that work with everything.",
	},
	{
		ID:          "21",
		Title:       "Linen Top - Breathable Comfort",
		Price:       69,
		Category:    "Tops",
		ImageURL:    "/images/tops/1.jpg",
		Description: "Perfect for warm weather. This linen top offers breathability and style.",
	},
	{
		ID:          "22",
		Title:       "Striped Shirt - Classic Pattern",
		Price:       89,
		Category:    "Tops",
		ImageURL:    "/images/tops/2.jpg",
		Description: "Nautical elegance. This striped shirt is a versatile piece that works in any season.",
	},
	{
		ID:          "23",
		Title:       "Oversized T-shirt - Comfort First",
		Price:       59,
		Category:    "Tops",
		ImageURL:    "/images/tops/3.jpg",
		Description: "Casual and comfortable. Perfect for everyday wear and relaxation.",
	},
	{
		ID:          "24",
		Title:       "Fitted Turtleneck - Winter Essential",
		Price:       99,
		Category:    "Tops",
		ImageURL:    "/images/tops/1.jpg",
		Description: "Timeless and elegant. This turtleneck is perfect for layering and makes any outfit sophisticated.",
	},
	{
		ID:          "25",
		Title:       "Button-Up Shirt - Work Ready",
		Price:       109,
		Category:    "Tops",
		ImageURL:    "/images/tops/2.jpg",
		Description: "Professional and polished. Perfect for the office and business settings.",
	},
	{
		ID:          "26",
		Title:       "Long Sleeve Tee - Everyday Basic",
		Price:       64,
		Category:    "Tops",
		ImageURL:    "/images/tops/3.jpg",
		Description: "Versatile and reliable. A wardrobe staple you'll reach for constantly.",
	},
	{
		ID:          "27",
		Title:       "Satin Blouse - Evening Elegance",
		Price:       139,
		Category:    "Tops",
		ImageURL:    "/images/tops/1.jpg",
		Description: "Sophisticated and luxurious. Perfect for evening events and special occasions.",
	},
	{
		ID:          "28",
		Title:       "Cropped Top - Modern Cut",
		Price:       74,
		Category:    "Tops",
		ImageURL:    "/images/tops/2.jpg",
		Description: "Contemporary and stylish. This cropped top works beautifully with high-waisted bottoms.",
	},
	{
		ID:          "29",
		Title:       "Henley Shirt - Casual Cool",
		Price:       84,
		Category:    "Tops",
		ImageURL:    "/images/tops/3.jpg",
		Description: "Laid-back style with an edge. Perfect for casual outings and weekends.",
	},

	// Bottoms (12 items)
	{
		ID:          "3",
		Title:       "Wide Leg Tailored Trousers - Seoul Studio",
		Price:       129,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/1.jpg",
		Description: "Contemporary silhouette with exceptional tailoring. These wide-leg trousers flatter all body types.",
	},
	{
		ID:          "30",
		Title:       "Slim Fit Jeans - Classic Denim",
		Price:       99,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/2.jpg",
		Description: "Timeless fit. These jeans work with everything and improve with age.",
	},
	{
		ID:          "31",
		Title:       "High Waisted Trousers - Modern Silhouette",
		Price:       139,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/3.jpg",
		Description: "Flattering and elegant. The perfect high-waisted trouser for any occasion.",
	},
	{
		ID:          "32",
		Title:       "Black Leggings - Essential Piece",
		Price:       59,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/1.jpg",
		Description: "Versatile and comfortable. Every wardrobe needs quality black leggings.",
	},
	{
		ID:          "33",
		Title:       "Straight Leg Jeans - Classic Style",
		Price:       109,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/2.jpg",
		Description: "Never out of style. These straight-leg jeans are a timeless essential.",
	},
	{
		ID:          "34",
		Title:       "Cropped Pants - Sophisticated Cut",
		Price:       119,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/3.jpg",
		Description: "Perfect proportions. These cropped pants work beautifully with any top.",
	},
	{
		ID:          "35",
		Title:       "Pleated Trousers - Elegant Detail",
		Price:       149,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/1.jpg",
		Description: "Sophisticated tailoring. The pleats add visual interest and dimension.",
	},
	{
		ID:          "36",
		Title:       "Flared Jeans - Retro Chic",
		Price:       119,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/2.jpg",
		Description: "Fashion-forward and fun. These flared jeans bring retro vibes to modern styling.",
	},
	{
		ID:          "37",
		Title:       "Tailored Shorts - Summer Ready",
		Price:       84,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/3.jpg",
		Description: "Sophisticated shorts perfect for warm weather and casual elegance.",
	},
	{
		ID:          "38",
		Title:       "Relaxed Fit Jeans - Comfortable Style",
		Price:       104,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/1.jpg",
		Description: "Comfort meets style. These relaxed-fit jeans are perfect for everyday wear.",
	},
	{
		ID:          "39",
		Title:       "Cigarette Pants - Sleek Fit",
		Price:       129,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/2.jpg",
		Description: "Sleek and streamlined. Perfect for creating a polished silhouette.",
	},
	{
		ID:          "40",
		Title:       "Bermuda Shorts - Classic Cut",
		Price:       94,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/3.jpg",
		Description: "Timeless elegance. These shorts work from day to night.",
	},

	// Knitwear (12 items)
	{
		ID:          "4",
		Title:       "Cashmere Blend Sweater - Korean Knit",
		Price:       149,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/1.jpg",
		Description: "Indulge in luxury with this cashmere blend knit. Soft, breathable, and designed to last.",
	},
	{
		ID:          "41",
		Title:       "Wool Turtleneck - Winter Warmth",
		Price:       129,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/2.jpg",
		Description: "Cozy and sophisticated. Perfect for cold weather layering.",
	},
	{
		ID:          "42",
		Title:       "Cotton Knit Sweater - Breathable",
		Price:       89,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/3.jpg",
		Description: "Light and versatile. Perfect for any season and any occasion.",
	},
	{
		ID:          "43",
		Title:       "Merino Wool Sweater - Premium Quality",
		Price:       159,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/1.jpg",
		Description: "Exceptional softness. Merino wool offers superior comfort and durability.",
	},
	{
		ID:          "44",
		Title:       "Chunky Knit Cardigan - Cozy Style",
		Price:       139,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/2.jpg",
		Description: "Warm and inviting. This chunky knit is perfect for creating comfort and style.",
	},
	{
		ID:          "45",
		Title:       "V-Neck Sweater - Versatile Basic",
		Price:       99,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/3.jpg",
		Description: "Classic and flattering. A V-neck sweater works with everything in your wardrobe.",
	},
	{
		ID:          "46",
		Title:       "Cable Knit Sweater - Textured Detail",
		Price:       119,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/1.jpg",
		Description: "Sophisticated texture. The cable knit adds visual interest and dimension.",
	},
	{
		ID:          "47",
		Title:       "Crew Neck Sweater - Essential Piece",
		Price:       94,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/2.jpg",
		Description: "A wardrobe staple. This crew neck sweater is reliable and timeless.",
	},
	{
		ID:          "48",
		Title:       "Lightweight Cardigan - Perfect Layer",
		Price:       109,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/3.jpg",
		Description: "Versatile layering piece. Perfect for creating dimension in any outfit.",
	},
	{
		ID:          "49",
		Title:       "Alpaca Blend Sweater - Ultra Soft",
		Price:       179,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/1.jpg",
		Description: "Incredibly soft and luxurious. Alpaca blend offers unmatched comfort.",
	},
	{
		ID:          "50",
		Title:       "Mock Neck Sweater - Modern Style",
		Price:       104,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/2.jpg",
		Description: "Contemporary silhouette. This mock neck offers sophistication and comfort.",
	},
	{
		ID:          "51",
		Title:       "Wrap Cardigan - Flattering Cut",
		Price:       129,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/3.jpg",
		Description: "Beautifully flattering. The wrap style is perfect for any body type.",
	},

	// Dresses (12 items)
	{
		ID:          "7",
		Title:       "Elegant Midi Dress - Korean Designer",
		Price:       169,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/1.jpg",
		Description: "Sophistication defined. This midi dress captures the essence of Korean minimalist design.",
	},
	{
		ID:          "52",
		Title:       "Classic Shift Dress - Timeless Style",
		Price:       139,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/2.jpg",
		Description: "Simple elegance. This shift dress works from office to evening.",
	},
	{
		ID:          "53",
		Title:       "Wrap Dress - Flattering Silhouette",
		Price:       159,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/3.jpg",
		Description: "Universally flattering. The wrap style emphasizes curves beautifully.",
	},
	{
		ID:          "54",
		Title:       "A-Line Dress - Feminine Cut",
		Price:       149,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/1.jpg",
		Description: "Soft and feminine. This A-line dress is perfect for any occasion.",
	},
	{
		ID:          "55",
		Title:       "Bodycon Dress - Sleek Fit",
		Price:       129,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/2.jpg",
		Description: "Confident and bold. This bodycon dress makes a statement.",
	},
	{
		ID:          "56",
		Title:       "Maxi Dress - Floor Length Elegance",
		Price:       189,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/3.jpg",
		Description: "Sophisticated elegance. Perfect for formal occasions and evening events.",
	},
	{
		ID:          "57",
		Title:       "Cocktail Dress - Evening Essential",
		Price:       179,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/1.jpg",
		Description: "Chic and sophisticated. Perfect for cocktail events and parties.",
	},
	{
		ID:          "58",
		Title:       "Shirt Dress - Casual Elegance",
		Price:       119,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/2.jpg",
		Description: "Versatile and chic. This shirt dress works as a dress or as a layering piece.",
	},
	{
		ID:          "59",
		Title:       "Pencil Dress - Sleek Silhouette",
		Price:       144,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/3.jpg",
		Description: "Professional and polished. Perfect for the office and business meetings.",
	},
	{
		ID:          "60",
		Title:       "Fit and Flare Dress - Playful Style",
		Price:       154,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/1.jpg",
		Description: "Fun and feminine. This fit and flare dress celebrates the female form.",
	},
	{
		ID:          "61",
		Title:       "Slip Dress - Minimalist Elegance",
		Price:       124,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/2.jpg",
		Description: "Effortlessly chic. Perfect for layering or wearing as a standalone piece.",
	},
	{
		ID:          "62",
		Title:       "Patterned Dress - Statement Piece",
		Price:       164,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/3.jpg",
		Description: "Bold and beautiful. This patterned dress makes a fashion statement.",
	},

	// Sets (12 items)
	{
		ID:          "6",
		Title:       "Coordinated Ensemble Set - Seoul Contemporary",
		Price:       159,
		Category:    "Sets",
		ImageURL:    "/images/sets/1.jpg",
		Description: "Take the guesswork out of styling with this thoughtfully coordinated set.",
	},
	{
		ID:          "8",
		Title:       "Contemporary Outfit Set - Seoul Studio",
		Price:       199,
		Category:    "Sets",
		ImageURL:    "/images/sets/2.jpg",
		Description: "Two pieces, endless possibilities. This contemporary set offers maximum versatility.",
	},
	{
		ID:          "63",
		Title:       "Classic Matching Set - Timeless Pairing",
		Price:       179,
		Category:    "Sets",
		ImageURL:    "/images/sets/3.jpg",
		Description: "Effortless coordination. This matching set takes the stress out of getting dressed.",
	},
	{
		ID:          "64",
		Title:       "Lounge Set - Comfort and Style",
		Price:       139,
		Category:    "Sets",
		ImageURL:    "/images/sets/1.jpg",
		Description: "Cozy yet chic. This lounge set is perfect for relaxed weekends at home.",
	},
	{
		ID:          "65",
		Title:       "Formal Two-Piece Set - Evening Ready",
		Price:       229,
		Category:    "Sets",
		ImageURL:    "/images/sets/2.jpg",
		Description: "Sophisticated pairing. Perfect for formal events and special occasions.",
	},
	{
		ID:          "66",
		Title:       "Casual Pair Set - Everyday Essential",
		Price:       129,
		Category:    "Sets",
		ImageURL:    "/images/sets/3.jpg",
		Description: "Go-to basics. This casual set works for everyday wear and endless styling options.",
	},
	{
		ID:          "67",
		Title:       "Business Set - Professional Pairing",
		Price:       199,
		Category:    "Sets",
		ImageURL:    "/images/sets/1.jpg",
		Description: "Office ready. This professional set makes creating work outfits effortless.",
	},
	{
		ID:          "68",
		Title:       "Knit Set - Cozy Coordinates",
		Price:       169,
		Category:    "Sets",
		ImageURL:    "/images/sets/2.jpg",
		Description: "Warm and comfortable. This knit set is perfect for cooler seasons.",
	},
	{
		ID:          "69",
		Title:       "Layered Set - Dimension and Style",
		Price:       189,
		Category:    "Sets",
		ImageURL:    "/images/sets/3.jpg",
		Description: "Create dimension. This layered set offers styling versatility.",
	},
	{
		ID:          "70",
		Title:       "Weekend Set - Relaxed Vibes",
		Price:       149,
		Category:    "Sets",
		ImageURL:    "/images/sets/1.jpg",
		Description: "Perfect for weekends. This casual set is comfortable and stylish.",
	},
	{
		ID:          "71",
		Title:       "Date Night Set - Elegant Pairing",
		Price:       219,
		Category:    "Sets",
		ImageURL:    "/images/sets/2.jpg",
		Description: "Impress on date night. This elegant set makes a lasting impression.",
	},
	{
		ID:          "72",
		Title:       "Transitional Set - Seasonal Bridge",
		Price:       159,
		Category:    "Sets",
		ImageURL:    "/images/sets/3.jpg",
		Description: "Perfect for transitional seasons. This set bridges spring and fall beautifully.",
	},
}
