package main

var products = []Product{
	{
		ID:          "1",
		Title:       "Oversized Linen Blazer - Seoul Collection",
		Price:       189,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/1.jpg",
		Description: "A modern take on the classic blazer. Crafted from premium linen, this oversized piece offers sophisticated elegance for every occasion. Perfect layering piece that transitions effortlessly from office to evening. Korean design excellence meets European minimalism.",
	},
	{
		ID:          "2",
		Title:       "Premium Cotton Shirt - Seoul Designer",
		Price:       79,
		Category:    "Tops",
		ImageURL:    "/images/tops/1.jpg",
		Description: "Timeless simplicity with impeccable attention to detail. This pristine white shirt is a wardrobe essential, crafted from the finest cotton for comfort and longevity. A piece designed to be worn for years, embodying the Korean philosophy of quality over quantity.",
	},
	{
		ID:          "3",
		Title:       "Wide Leg Tailored Trousers - Seoul Studio",
		Price:       129,
		Category:    "Bottoms",
		ImageURL:    "/images/bottoms/1.jpg",
		Description: "Contemporary silhouette with exceptional tailoring. These wide-leg trousers flattera all body types while maintaining an effortlessly chic aesthetic. Designed for the modern woman who values comfort without compromising on style.",
	},
	{
		ID:          "4",
		Title:       "Cashmere Blend Sweater - Korean Knit",
		Price:       149,
		Category:    "Knitwear",
		ImageURL:    "/images/knitwear/1.jpg",
		Description: "Indulge in luxury with this cashmere blend knit. Soft, breathable, and designed to last, this sweater represents Korean excellence in textile craftsmanship. Layer it, wear it solo, or pair with tailored trousers for effortless elegance.",
	},
	{
		ID:          "5",
		Title:       "Structured Wool Coat - Seoul Designer",
		Price:       299,
		Category:    "Outerwear",
		ImageURL:    "/images/outerwear/2.jpg",
		Description: "The ultimate investment piece. This structured wool coat combines Korean minimalism with European sophistication. Meticulously crafted from premium wool, it's designed to become your go-to layer season after season. A true wardrobe heirloom.",
	},
	{
		ID:          "6",
		Title:       "Coordinated Ensemble Set - Seoul Contemporary",
		Price:       159,
		Category:    "Sets",
		ImageURL:    "/images/sets/1.jpg",
		Description: "Take the guesswork out of styling with this thoughtfully coordinated set. Curated by Korean designers for maximum versatility, each piece works individually or together for a cohesive, effortless look.",
	},
	{
		ID:          "7",
		Title:       "Elegant Midi Dress - Korean Designer",
		Price:       169,
		Category:    "Dresses",
		ImageURL:    "/images/dresses/1.jpg",
		Description: "Sophistication defined. This midi dress captures the essence of Korean minimalist design—understated elegance with impeccable construction. Perfect for work, evening events, or any occasion where you want to make a quiet statement.",
	},
	{
		ID:          "8",
		Title:       "Contemporary Outfit Set - Seoul Studio",
		Price:       199,
		Category:    "Sets",
		ImageURL:    "/images/sets/2.jpg",
		Description: "Two pieces, endless possibilities. This contemporary set from a Seoul-based designer offers the flexibility modern women demand. Mix, match, or wear as intended—either way, you'll have a collection of pieces you'll reach for again and again.",
	},
}
